<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\QuestionTitle;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $questions = [
            ['title' => 'Considering what was reported in the 2025 TIP Report country narrative profile section, have there been any changes to human trafficking trends, drivers, methods, foreign victim nationalities, source/destination dynamics, sectors, affected demographics, etc. during the reporting period? Please report the profile of victims at particular risk of sex trafficking or labor trafficking, including any changes since the last reporting period (e.g., men, women, children, migrants, certain ethnic groups). Please note whether there was labor trafficking or sex trafficking by narcotics traffickers, migrants and those with a migration background, and gangs. [NOTE: Include new information relevant to the April 1, 2025-March 31, 2026, period. End Note]',   'status' => 1],
            ['title' => 'Are any of the following persons present in the country as part of government-to-government agreements and/or in foreign government-affiliated projects? If present, are these individuals subjected to or at high risk of forced labor? · Chinese Nationals (incl. in Belt and Road Initiative) · Cuban Nationals (incl. medical workers, athletes, coaches, artists, teachers, engineers, sea merchants, and others) · North Korean Nationals (incl. in the following locations): Algeria, Angola, Benin, Cambodia, China, Cote d’Ivoire, the Democratic Republic of the Congo, Equatorial Guinea, Georgia, Guinea, Laos, Mali, Mauritius, Republic of Congo, Russia, Senegal, Uganda, United Arab Emirates, Vietnam, Zambia, and Zimbabwe.', 'status' => 0],
            ['title' => 'Technology and Trafficking: If applicable, describe how traffickers use technology to recruit and exploit victims and how governments combat these forms of human trafficking, particularly on emerging issues. Please report on: · Fraudulent Recruitment – Have nationals been fraudulently recruited to participate in online scam operations or to fight in or support active conflicts? What tech tools do traffickers use to recruit victims? Examples include social media, phone apps, and online job portals. · Means – How do traffickers use technology to force, deceive, or coerce victims? Examples include bar code tattooing, the use of location-tracking applications and devices, and sextortion. · Forms of Exploitation – In which industries or practices do traffickers exploit victims? Examples can include tech-enabled exploitation, such as cyber or online scam operations or livestreamed commercial sex acts. For online scam operations, describe any involving indicators of trafficking identified during the reporting period, while including information on the victims’ nationalities, the government’s response, and victim repatriation efforts. · Emerging Trends – What types of emerging technology do traffickers use to facilitate trafficking? Examples include use of cryptocurrencies to process financial transactions, use of the dark web to conceal activities, or artificial intelligence. Government Response — How are governments countering tech-enabled trafficking? What efforts are governments making to address needs of victims of technology-facilitated human trafficking (e.g., to remove exploitative materials from online platforms, provide digital security assistance, or offer psychosocial support)? Examples include police units trained in digital evidence collection, “web crawlers” to identify suspicious internet activity, data analytics and supply chain tracing, collaboration with social media or technology companies, and internet safety sensitization campaigns.',  'status' => 0],
            ['title' => 'What changes, if any, to preexisting anti-trafficking legislation took place during the reporting period (amendments to laws or penal codes, new laws, sentencing guidelines, presidential decrees, court precedents, etc.)? List the changes and attach the text(s) in the original language (and in English, if available)',    'status' => 1],
            ['title' => 'Were law enforcement, military, diplomatic, security, state or municipal employees, or other officials or state institutions involved directly in trafficking? Describe any allegations of official complicity in trafficking crimes, including state-sponsored forced labor',    'status' => 1],
            ['title' => 'Was official involvement in trafficking crimes part of a national directive or policy, including state-sponsored forced labor?', 'status' => 1],
            ['title' => 'Were law enforcement, military, security, state or municipal employees, or other officials allegedly facilitating the crime or obstructing justice (e.g., taking bribes)?', 'status' => 1],
            ['title' => 'Did the government investigate, prosecute, convict, or sentence any allegedly complicit officials? Did the government fine or demote any allegedly complicit officials?', 'status' => 1],
            ['title' => 'Considering what was reported in the 2025 TIP Report country narrative prosecution section, were there any changes to government units/courts responsible for investigating, prosecuting, or hearing trafficking cases, and were any of these units and their staff exclusively dedicated to trafficking, or was trafficking among other responsibilities/mandates? Did these units/courts have adequate resources and adequately cover all jurisdictions?', 'status' => 1],
            ['title' => 'Were there any gaps in law enforcement’s ability to investigate, prosecute, or convict traffickers? Did law enforcement investigate trafficking crimes as other offenses and/or did prosecutors charge alleged traffickers under alternative criminal provisions with lesser penalties (e.g., commercial sex crimes, smuggling of migrants, labor violations, fraud, etc.)?', 'status' => 1],
            ['title' => 'Describe efforts made by the government to train officials on anti-trafficking enforcement, policies, or laws and include the number and type of officials trained and training topics. Describe who funded and implemented the training, including any in-kind support from the government.',    'status' => 1],
            ['title' => 'Did the government cooperate with the United States, foreign counterparts, or international law enforcement organizations on any trafficking-related law enforcement activities? If so, how many new investigations, prosecutions, etc. resulted from this cooperation, including extraditions? Does the government extradite persons charged with trafficking crimes in substantially the same way as persons charged with other serious crimes? Include a description of relevant cases. Were these investigations/prosecutions/convictions included in the Appendix 1: Law Enforcement Data chart?',    'status' => 1],
            ['title' => 'Did the government enter into new bilateral, multilateral, or regional enforcement or coordination arrangements, or partnerships with NGOs or private sector entities? If so, please describe.',  'status' => 0],
            ['title' => 'Considering what was reported in the 2025 TIP Report country narrative protection section, have there been any new (or changes to preexisting) formal/standard procedures for victim identification? If so, please describe.', 'status' => 1],
            ['title' => 'Did front-line officials have a victim identification protocol or other formal written procedures to guide proactive victim identification? Does the protocol or other formal written procedure outline steps to screen populations at increased risk of trafficking per the previous year’s TIP Report or other reporting on emerging trends involving the country or its nationals? Share copies of the victim identification protocol or any formal written procedures used for victim identification, if any.',    'status' => 0],
            ['title' => 'Describe efforts taken by authorities to consistently and systematically use such protocols or formal written procedures to proactively screen for indicators of human trafficking. (Note: Individual sectors may have separate, tailored procedures, or multiple government sectors may use the same protocol.) Describe efforts, if any, to train front-line officials on use of the victim identification protocol or formal written procedures.',    'status' => 0],
            ['title' => 'Considering what was reported in the 2025 TIP Report country narrative protection section, have there been any new or modified procedures for victim referral to protection services? If there are no standard procedures, explain how government entities ensure victims are referred to care.',    'status' => 1],
            ['title' => 'Were front-line officials across government sectors, and all other responsible parties trained on and systematically using such protocols and was implementation similar across all populations? If victims were referred to NGO facilities, describe the NGOs’ assessment of the government referral process',    'status' => 1],
            ['title' => 'Describe the process by which victims were referred to social service providers, including if they interacted with law enforcement first, and any gaps or difficulties in the process.',    'status' => 1],
            ['title' => 'Describe any government-operated or -funded trafficking-specific hotlines or other similar mechanisms, where members of the public could directly reach and receive assistance from first responders. What were the days/hours of operation and language services available, and were operators trained on victim screening and referral? Did calls to government-run or -funded hotlines or other similar mechanisms lead to victim identification, referral to care, and/or criminal investigations? How many calls were received and how many resulted in referrals?',    'status' => 1],
            ['title' => 'Considering what was reported in the 2025 TIP Report country narrative protection section, have there been any new or modified services available for victim care (including shelter, medical care, counseling, legal services, and repatriation assistance)? Provide details on the types of services the government provided or funded for trafficking victims. Do not include NGO services delivered unless the government funded the organizations. If the government operated or funded shelters: Please indicate how many shelters there were and how many victims each shelter could accommodate; describe if such shelters were specialized for trafficking victims or if they also served other populations; note which government entity or NGO operated the shelter; and which groups of victims were eligible to reside in each respective shelter (i.e., adults/children; men/women; victims of forced labor/sex trafficking; country nationals/foreign nationals).',    'status' => 1],
            ['title' => 'Did other stakeholders, including NGOs, IOs, or community/religious based organizations fund and operate shelters available to trafficking victims? If so, how many NGO shelters serving trafficking victims were there and which groups of victims were eligible to reside in the shelter(s)?',    'status' => 1],
            ['title' => 'Were there reports or allegations of misconduct or mistreatment by shelter staff, or unsafe conditions in government or nongovernmental shelters? If so, what action did the government take to address these allegations?',    'status' => 1],
            ['title' => 'Describe if victim services were general or specialized to trafficking victims’ needs and describe the overall quality of victim care. Indicate if all trafficking survivors could access the same quality and level of services or if only certain groups were eligible. Add any additional details on quality of services, improvements made, and challenges, shortcomings, or gaps (i.e., who may be eligible to access services) in providing the care.',    'status' => 1],
            ['title' => 'Did government policy require a person to be formally identified as a trafficking victim to receive certain services or benefits? If so, which services or benefits were limited to persons formally identified as trafficking victims? If applicable, which officials were authorized to formally designate individuals as trafficking victims?',    'status' => 1],
            ['title' => 'Did service providers receive adequate training on providing care to trauma survivors? Did service providers have the knowledge and skills to support victims through a consistent victim-centered approach?',    'status' => 1],
            ['title' => 'How much funding (in the local currency) did the government spend on direct victim care and assistance (e.g., funds for government shelters or payments to victims). If assistance was in-kind, please describe. Note if any NGOs or IOs fund the government’s victim assistance',    'status' => 1],
            ['title' => 'Child Victims: Describe shelter options available specifically for child trafficking victims, including non-specialized shelters, such as homeless shelters, group homes, migrant shelters, or juvenile justice detention centers. Indicate what kind of specialized care child victims received in these shelters, and if children had a choice among shelter options or could leave shelters to attend school. Which entity determined whether a child trafficking victim was placed into a shelter, returned to their family, or placed in another arrangement such as with a foster family, and did these authorities receive training on trafficking and the vulnerabilities of child trauma survivors? Indicate if authorities returned child victims to live with family members who may have been involved in their exploitation or how authorities prevented children from returning to situations of exploitation.',    'status' => 1],
            ['title' => 'Adult Victims: Did the government provide services to adult victims who declined to reside in shelters?',    'status' => 1],
            ['title' => 'Foreign Victims: What services were foreign victims of trafficking entitled to? Did the country have a significant percentage of foreign victims of trafficking?',    'status' => 1],
            ['title' => 'Citizen Victims Abroad: Did the government fund the voluntary repatriation of their citizens victimized abroad? If so, how many victims received this support? Were they referred to services upon their return? Do not include cases funded by IOs or foreign governments.',    'status' => 1],
            ['title' => 'Were potential trafficking victims inappropriately incarcerated, fined, or otherwise penalized solely for unlawful acts committed as a direct result of being trafficked (e.g., subject to commercial sex, drug-related, or other criminal charges, or subject to deportation/immigration enforcement or administrative penalties)? Why did the government and/or the courts incarcerate, fine, or otherwise penalize victims?',    'status' => 1],
            ['title' => 'Did the government monitor immigration and emigration patterns for signs of trafficking, and did law enforcement respond to any such evidence in a manner consistent with the vigorous investigation and prosecution of trafficking and protection of victims?',    'status' => 1],
            ['title' => 'How many newly identified victims participated in the investigation and prosecution of traffickers? What, if any, support did the government provide to victims who assisted in the investigation and prosecution of trafficking cases, such as visa categories that facilitate cooperation with law enforcement, legal support and advice, witness protection, and victim-witness advocates?',    'status' => 1],
            ['title' => 'Were victims required to speak with law enforcement officials, or cooperate with authorities in the investigation or prosecution of traffickers to access certain protection services (such as residence in a government shelter? Did the government provide a recovery and reflection period to all victims? What, if any, alternatives were victims presented with to speaking with law enforcement while participating in investigations?',    'status' => 1],
            ['title' => 'Did law enforcement consistently conduct victim interviews in private, secure locations, without any suspects present? Did the government provide interpreters to conduct interviews in an individual’s primary language or utilize any facilities specially equipped to support victim’s needs (e.g., child-friendly interviewing rooms, one-way mirror/Gessell chambers)?',    'status' => 1],
            ['title' => 'What, if any, legal assistance did the government fund and provide to trafficking victims? What, if any, forms of legal aid did it offer to assist with cases on related legal matters, such as criminal charges, family law or protective orders, etc.?',    'status' => 1],
            ['title' => 'What forms of victim-witness protection services did the government provide to protect participating victims’ physical security and privacy during proceedings? Could victims provide testimony via video or written statements? How many, if any, participated via these methods? What, if any, accommodations did the government provide for victims with disabilities during trials? Were there any gaps in how protective protocols were implemented?',    'status' => 1],
            ['title' => 'Could victims obtain restitution from defendants in criminal cases? Were criminal justice officials adequately trained to seek and order restitution for victims during criminal cases and did they do so?',    'status' => 1],
            ['title' => 'Could victims file civil suits against traffickers for damages? Did the government provide information or legal support for victims to pursue a civil suit?',    'status' => 1],
            ['title' => 'How many convicted traffickers were ordered to pay restitution to a victim and what amounts were they ordered to pay? How many victims received the amount they were awarded? If applicable, what factors hindered victims’ receipt of these funds?',    'status' => 1],
            ['title' => 'Which official, agency, and/or national coordinating body, if any, led government anti-trafficking efforts? How was this body effective or ineffective, and what results did it produce? How often did it meet during the reporting period?',    'status' => 1],
            ['title' => 'Did the government seek civil society and/or survivors’ input in crafting or implementing any new anti-trafficking laws, regulations, policies, programs?',    'status' => 1],
            ['title' => 'How much funding (in the local currency) did the government spend on prevention efforts (e.g., awareness campaigns, research projects, national action plan implementation, etc.)? Specify if prevention funding came from a national, state, or local budget. If assistance was in-kind, describe.',    'status' => 1],
            ['title' => 'Did the government create or update a national action plan to address trafficking? If yes, provide a copy (in English, if available). Describe the plan and/or specific updates, including the timeframe as well as leads, plans, and funding for its implementation.',    'status' => 1],
            ['title' => 'Did the government fund and/or conduct awareness activities, or contribute in-kind resources to NGO or IO awareness campaigns? Note if these activities were new or ongoing and if readily available to intended audiences, cost-free, and accessible in various languages, including braille.',    'status' => 1],
            ['title' => 'Did the government change how it regulated and oversaw labor recruitment for licensed and unlicensed recruitment agencies, individual recruiters, and sub-brokers? If yes, please describe.',    'status' => 1],
            ['title' => 'Did the government prohibit worker-paid recruitment fees? If yes, explain how it enforced bans on recruitment fees. If no, describe any rules surrounding worker-paid recruitment fees.',    'status' => 1],
            ['title' => 'Did the government have agreements, with a transparent oversight mechanism, with other countries on safe and responsible labor recruitment that included measures to prevent trafficking vulnerable people seeking work in those countries, or a prohibition on importing goods made with forced labor? Were these agreements or prohibitions implemented during the reporting period?',    'status' => 1],
            ['title' => 'Did the government have mechanisms to prevent trafficking by employers in migrant worker programs? Describe the process by which migrants could seek to leave employers based on exploitative treatment.',    'status' => 1],
            ['title' => 'What measures not mentioned elsewhere did the government take to reduce the demand for commercial sex acts by targeting consumers and/or discourage the purchase of commercial sex within legal or decriminalized “prostitution” activities? (NOTE: These measures should target consumers – not suppliers or facilitators – of commercial sex. Law enforcement efforts against brothels or individuals in commercial sex are not considered efforts to reduce the demand for commercial sex.)',    'status' => 1],
            ['title' => 'Did the government prosecute, deport, and/or convict host country nationals or foreigners participating in domestic and extraterritorial child sexual exploitation? Did authorities identify victims of child sex trafficking exploited by domestic or foreign tourists during the reporting period? If so, please provide details on where such exploitation occurred and of whom and by whom.',    'status' => 1],
            ['title' => 'Did the government train its diplomats not to engage in or facilitate trafficking? If yes, please describe.',    'status' => 1],
            ['title' => 'Did country diplomats allegedly exploit domestic workers overseas (e.g., through force, fraud, or coercion; or through worker pay that is substantially lower than prevailing wages in the host country, given in the form of food and/or accommodation, or withheld)? Please describe. Did the government seek criminal accountability?',    'status' => 1],
            ['title' => 'Did the government provide anti-trafficking training to its nationals deployed abroad on peacekeeping or other similar missions?',    'status' => 1],
            ['title' => 'In instances of trafficking allegations filed against peacekeepers, what steps did the government take to hold perpetrators accountable',    'status' => 1],
            ['title' => 'Considering what was reported in the 2025 TIP Report country narrative, provide any updates about trafficking trends, government anti-trafficking efforts in territories or semi-autonomous regions, and lead agencies.',    'status' => 1],
            ['title' => 'Describe any trafficking investigations and prosecutions, victims identified and referred to care, and available funding in territories or semi-autonomous regions or in a disputed territory within the geographic bounds of the country.',    'status' => 1],


        ];

        foreach ($questions as $question) {
            QuestionTitle::create([
                'title'   => $question['title'],
                'status' => $question['status'],
            ]);
        }
    }
}
