<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class UpazilaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $upzilas_list = [
                ['name' => 'Dhamrai', 'bn_name' => 'ধামরাই', 'distric_id' => 1],
                ['name' => 'Dohar', 'bn_name' => 'দোহার', 'distric_id' => 1],
                ['name' => 'Keraniganj', 'bn_name' => 'কেরানীগঞ্জ', 'distric_id' => 1],
                ['name' => 'Nawabganj', 'bn_name' => 'নবাবগঞ্জ', 'distric_id' => 1],
                ['name' => 'Savar', 'bn_name' => 'সাভার', 'distric_id' => 1],
                ['name' => 'Gazipur Sadar', 'bn_name' => 'গাজীপুর সদর', 'distric_id' => 2],
                ['name' => 'Kaliakair', 'bn_name' => 'কালিয়াকৈইর', 'distric_id' => 2],
                ['name' => 'Kapasia', 'bn_name' => 'কাপাসিয়া', 'distric_id' => 2],
                ['name' => 'Sreepur', 'bn_name' => 'শ্রীপুর', 'distric_id' => 2],
                ['name' => 'Tongi', 'bn_name' => 'টঙ্গী', 'distric_id' => 2],
                ['name' => 'Narayanganj Sadar', 'bn_name' => 'নারায়ণগঞ্জ সদর', 'distric_id' => 3],
                ['name' => 'Bandar', 'bn_name' => 'বন্দর', 'distric_id' => 3],
                ['name' => 'Rupganj', 'bn_name' => 'রূপগঞ্জ', 'distric_id' => 3],
                ['name' => 'Sonargaon', 'bn_name' => 'সোনারগাঁও', 'distric_id' => 3],
                ['name' => 'Araihazar', 'bn_name' => 'আড়াইহাজার', 'distric_id' => 3],
                ['name' => 'Manikganj Sadar', 'bn_name' => 'মানিকগঞ্জ সদর', 'distric_id' => 4],
                ['name' => 'Saturia', 'bn_name' => 'সাটুরিয়া', 'distric_id' => 4],
                ['name' => 'Shibalaya', 'bn_name' => 'শিবালয়', 'distric_id' => 4],
                ['name' => 'Singair', 'bn_name' => 'সিঙ্গাইর', 'distric_id' => 4],
                ['name' => 'Harirampur', 'bn_name' => 'হরিরামপুর', 'distric_id' => 4],
                ['name' => 'Ghior', 'bn_name' => 'ঘিওর', 'distric_id' => 4],
                ['name' => 'Daulatpur', 'bn_name' => 'দৌলতপুর', 'distric_id' => 4],
                ['name' => 'Munshiganj Sadar', 'bn_name' => 'মুন্সীগঞ্জ সদর', 'distric_id' => 5],
                ['name' => 'Sreenagar', 'bn_name' => 'শ্রীনগর', 'distric_id' => 5],
                ['name' => 'Sirajdikhan', 'bn_name' => 'সিরাজদিখান', 'distric_id' => 5],
                ['name' => 'Lohajang', 'bn_name' => 'লৌহজং', 'distric_id' => 5],
                ['name' => 'Gazaria', 'bn_name' => 'গাজরিয়া', 'distric_id' => 5],
                ['name' => 'Tongibari', 'bn_name' => 'টঙ্গিবাড়ি', 'distric_id' => 5],
                ['name' => 'Kishoreganj Sadar', 'bn_name' => 'কিশোরগঞ্জ সদর', 'distric_id' => 6],
                ['name' => 'Bhairab', 'bn_name' => 'ভৈরব', 'distric_id' => 6],
                ['name' => 'Hossainpur', 'bn_name' => 'হোসেনপুর', 'distric_id' => 6],
                ['name' => 'Itna', 'bn_name' => 'ইটনা', 'distric_id' => 6],
                ['name' => 'Karimganj', 'bn_name' => 'করিমগঞ্জ', 'distric_id' => 6],
                ['name' => 'Katiadi', 'bn_name' => 'কটিয়াদি', 'distric_id' => 6],
                ['name' => 'Mithamain', 'bn_name' => 'মিঠামইন', 'distric_id' => 6],
                ['name' => 'Nikli', 'bn_name' => 'নিকলী', 'distric_id' => 6],
                ['name' => 'Kuliarchar', 'bn_name' => 'কুলিয়ারচর', 'distric_id' => 6],
                ['name' => 'Tangail Sadar', 'bn_name' => 'টাঙ্গাইল সদর', 'distric_id' => 7],
                ['name' => 'Basail', 'bn_name' => 'বাসাইল', 'distric_id' => 7],
                ['name' => 'Bhuapur', 'bn_name' => 'ভুুয়াপুর', 'distric_id' => 7],
                ['name' => 'Delduar', 'bn_name' => 'দেলদুয়ার', 'distric_id' => 7],
                ['name' => 'Dhanbari', 'bn_name' => 'ধানবাড়ি', 'distric_id' => 7],
                ['name' => 'Gopalpur', 'bn_name' => 'গোপালপুর', 'distric_id' => 7],
                ['name' => 'Ghatail', 'bn_name' => 'ঘাটাইল', 'distric_id' => 7],
                ['name' => 'Kalihati', 'bn_name' => 'কালিহাতি', 'distric_id' => 7],
                ['name' => 'Madhupur', 'bn_name' => 'মধুপুর', 'distric_id' => 7],
                ['name' => 'Mirzapur', 'bn_name' => 'মির্জাপুর', 'distric_id' => 7],
                ['name' => 'Sakhipur', 'bn_name' => 'সখিপুর', 'distric_id' => 7],
                ['name' => 'Gopalpur', 'bn_name' => 'গোপালপুর', 'distric_id' => 7],
                ['name' => 'Faridpur Sadar', 'bn_name' => 'ফরিদপুর সদর', 'distric_id' => 8],
                ['name' => 'Alfadanga', 'bn_name' => 'আলফাডাঙ্গা', 'distric_id' => 8],
                ['name' => 'Boalmari', 'bn_name' => 'বোয়ালমারি', 'distric_id' => 8],
                ['name' => 'Bhanga', 'bn_name' => 'ভাঙ্গা', 'distric_id' => 8],
                ['name' => 'Charbhadrasan', 'bn_name' => 'চরভদ্রাসন', 'distric_id' => 8],
                ['name' => 'Madhukhali', 'bn_name' => 'মধুখালী', 'distric_id' => 8],
                ['name' => 'Nagarkanda', 'bn_name' => 'নগরকান্দা', 'distric_id' => 8],
                ['name' => 'Saltha', 'bn_name' => 'সালথা', 'distric_id' => 8],
                ['name' => 'Madaripur Sadar', 'bn_name' => 'মাদারীপুর সদর', 'distric_id' => 9],
                ['name' => 'Kalkini', 'bn_name' => 'কালকিনি', 'distric_id' => 9],
                ['name' => 'Rajoir', 'bn_name' => 'রাজৈর', 'distric_id' => 9],
                ['name' => 'Shibchar', 'bn_name' => 'শিবচর', 'distric_id' => 9],
                ['name' => 'Shariatpur Sadar', 'bn_name' => 'শরীয়তপুর সদর', 'distric_id' => 10],
                ['name' => 'Bhedarganj', 'bn_name' => 'ভেদরগঞ্জ', 'distric_id' => 10],
                ['name' => 'Gosairhat', 'bn_name' => 'গোসাইরহাট', 'distric_id' => 10],
                ['name' => 'Naria', 'bn_name' => 'নড়িয়া', 'distric_id' => 10],
                ['name' => 'Zajira', 'bn_name' => 'জাজিরা', 'distric_id' => 10],
                ['name' => 'Rajbari Sadar', 'bn_name' => 'রাজবাড়ী সদর', 'distric_id' => 11],
                ['name' => 'Baliakandi', 'bn_name' => 'বালিয়াকান্দি', 'distric_id' => 11],
                ['name' => 'Kalukhali', 'bn_name' => 'কালুখালি', 'distric_id' => 11],
                ['name' => 'Pangsha', 'bn_name' => 'পাংশা', 'distric_id' => 11],
                ['name' => 'Goalanda', 'bn_name' => 'গোয়ালন্দা', 'distric_id' => 11],
                ['name' => 'Narsingdi Sadar', 'bn_name' => 'নরসিংদী সদর', 'distric_id' => 12],
                ['name' => 'Belabo', 'bn_name' => 'বেলাবো', 'distric_id' => 12],
                ['name' => 'Monohardi', 'bn_name' => 'মনোহরদী', 'distric_id' => 12],
                ['name' => 'Raipura', 'bn_name' => 'রায়পুরা', 'distric_id' => 12],
                ['name' => 'Shibpur', 'bn_name' => 'শিবপুর', 'distric_id' => 12],
                ['name' => 'Netrokona Sadar', 'bn_name' => 'নেত্রকোনা সদর', 'distric_id' => 13],
                ['name' => 'Purbadhala', 'bn_name' => 'পূর্বধলা', 'distric_id' => 13],
                ['name' => 'Mohanganj', 'bn_name' => 'মোহনগঞ্জ', 'distric_id' => 13],
                ['name' => 'Durgapur', 'bn_name' => 'দুর্গাপুর', 'distric_id' => 13],
                ['name' => 'Atpara', 'bn_name' => 'আটপাড়া', 'distric_id' => 13],
                ['name' => 'Kalmakanda', 'bn_name' => 'কালমাকান্দা', 'distric_id' => 13],
                ['name' => 'Khaliajuri', 'bn_name' => 'খালিয়াজুরি', 'distric_id' => 13],
                ['name' => 'Chattogram Sadar', 'bn_name' => 'চট্টগ্রাম সদর', 'distric_id' => 14],
                ['name' => 'Pahartali', 'bn_name' => 'পাহাড়তলী', 'distric_id' => 14],
                ['name' => 'Double Mooring', 'bn_name' => 'ডবলমুরিং', 'distric_id' => 14],
                ['name' => 'Kotwali', 'bn_name' => 'কোতোয়ালী', 'distric_id' => 14],
                ['name' => 'Cumilla Sadar', 'bn_name' => 'কুমিল্লা সদর', 'distric_id' => 15],
                ['name' => 'Barura', 'bn_name' => 'বড়ুড়া', 'distric_id' => 15],
                ['name' => 'Brahmanpara', 'bn_name' => 'ব্রাহ্মণপাড়া', 'distric_id' => 15],
                ['name' => 'Chandina', 'bn_name' => 'চান্দিনা', 'distric_id' => 15],
                ['name' => 'Daudkandi', 'bn_name' => 'দাউদকান্দি', 'distric_id' => 15],
                ['name' => 'Debidwar', 'bn_name' => 'দেবিদ্বার', 'distric_id' => 15],
                ['name' => 'Homna', 'bn_name' => 'হোমনা', 'distric_id' => 15],
                ['name' => 'Laksam', 'bn_name' => 'লাকসাম', 'distric_id' => 15],
                ['name' => 'Meghna', 'bn_name' => 'মেঘনা', 'distric_id' => 15],
                ['name' => 'Monohorgonj', 'bn_name' => 'মনোহরগঞ্জ', 'distric_id' => 15],
                ['name' => 'Nangalkot', 'bn_name' => 'নাঙ্গলকোট', 'distric_id' => 15],
                ['name' => 'Rangamati Sadar', 'bn_name' => 'রাঙ্গামাটি সদর', 'distric_id' => 16],
                ['name' => 'Baghaichhari', 'bn_name' => 'বাঘাইছড়ি', 'distric_id' => 16],
                ['name' => 'Barkal', 'bn_name' => 'বকখাল', 'distric_id' => 16],
                ['name' => 'Kawkhali', 'bn_name' => 'কাউখালী', 'distric_id' => 16],
                ['name' => 'Rajasthali', 'bn_name' => 'রাজস্থলী', 'distric_id' => 16],
                ['name' => 'Belaichhari', 'bn_name' => 'বেলাইছড়ি', 'distric_id' => 16],
                ['name' => 'Kaptai', 'bn_name' => 'কাপ্তাই', 'distric_id' => 16],
                ['name' => 'Khagrachhari Sadar', 'bn_name' => 'খাগড়াছড়ি সদর', 'distric_id' => 17],
                ['name' => 'Dighinala', 'bn_name' => 'দিঘিনালা', 'distric_id' => 17],
                ['name' => 'Panchhari', 'bn_name' => 'পানছড়ি', 'distric_id' => 17],
                ['name' => 'Lakshmichhari', 'bn_name' => 'লক্ষ্মীছড়ি', 'distric_id' => 17],
                ['name' => 'Mahalchhari', 'bn_name' => 'মহালছড়ি', 'distric_id' => 17],
                ['name' => 'Ramgarh', 'bn_name' => 'রামগড়', 'distric_id' => 17],
                ['name' => 'Bandarban Sadar', 'bn_name' => 'বান্দরবান সদর', 'distric_id' => 18],
                ['name' => 'Thanchi', 'bn_name' => 'থানচি', 'distric_id' => 18],
                ['name' => 'Ruma', 'bn_name' => 'রুমা', 'distric_id' => 18],
                ['name' => 'Lama', 'bn_name' => 'লামা', 'distric_id' => 18],
                ['name' => 'Rowangchhari', 'bn_name' => 'রোয়াংছড়ি', 'distric_id' => 18],
                ['name' => 'Alikadam', 'bn_name' => 'আলীকদম', 'distric_id' => 18],
                ['name' => 'Brahmanbaria Sadar', 'bn_name' => 'ব্রাহ্মণবাড়িয়া সদর', 'distric_id' => 19],
                ['name' => 'Kasba', 'bn_name' => 'কসবা', 'distric_id' => 19],
                ['name' => 'Nabinagar', 'bn_name' => 'নবীনগর', 'distric_id' => 19],
                ['name' => 'Sarail', 'bn_name' => 'সারাইল', 'distric_id' => 19],
                ['name' => 'Ashuganj', 'bn_name' => 'আশুগঞ্জ', 'distric_id' => 19],
                ['name' => 'Bancharampur', 'bn_name' => 'বাঞ্ছারামপুর', 'distric_id' => 19],
                ['name' => 'Bijoynagar', 'bn_name' => 'বিজয়নগর', 'distric_id' => 19],
                ['name' => 'Chandpur Sadar', 'bn_name' => 'চাঁদপুর সদর', 'distric_id' => 20],
                ['name' => 'Haimchar', 'bn_name' => 'হাইমচর', 'distric_id' => 20],
                ['name' => 'Kachua', 'bn_name' => 'কচুয়া', 'distric_id' => 20],
                ['name' => 'Faridganj', 'bn_name' => 'ফরিদগঞ্জ', 'distric_id' => 20],
                ['name' => 'Shahrasti', 'bn_name' => 'শাহরাস্তি', 'distric_id' => 20],
                ['name' => 'Feni Sadar', 'bn_name' => 'ফেনী সদর', 'distric_id' => 21],
                ['name' => 'Chhagalnaiya', 'bn_name' => 'ছাগলনাইয়া', 'distric_id' => 21],
                ['name' => 'Parshuram', 'bn_name' => 'পরশুরাম', 'distric_id' => 21],
                ['name' => 'Fulgazi', 'bn_name' => 'ফুলগাজী', 'distric_id' => 21],
                ['name' => 'Daganbhuiyan', 'bn_name' => 'দাগনভূইয়া', 'distric_id' => 21],
                ['name' => 'Sonagazi', 'bn_name' => 'সোনাগাজী', 'distric_id' => 21],
                ['name' => 'Lakshmipur Sadar', 'bn_name' => 'লক্ষ্মীপুর সদর', 'distric_id' => 22],
                ['name' => 'Raipur', 'bn_name' => 'রায়পুর', 'distric_id' => 22],
                ['name' => 'Ramganj', 'bn_name' => 'রামগঞ্জ', 'distric_id' => 22],
                ['name' => 'Ramgati', 'bn_name' => 'রামগতি', 'distric_id' => 22],
                ['name' => 'Kamalnagar', 'bn_name' => 'কমলনগর', 'distric_id' => 22],
                ['name' => 'Noakhali Sadar', 'bn_name' => 'নোয়াখালি সদর', 'distric_id' => 23],
                ['name' => 'Companiganj', 'bn_name' => 'কোম্পানিগঞ্জ', 'distric_id' => 23],
                ['name' => 'Chatkhil', 'bn_name' => 'চাটখিল', 'distric_id' => 23],
                ['name' => 'Begumganj', 'bn_name' => 'বেগমগঞ্জ', 'distric_id' => 23],
                ['name' => 'Hatiya', 'bn_name' => 'হাতিয়া', 'distric_id' => 23],
                ['name' => 'Cox\'s Bazar Sadar', 'bn_name' => 'কক্সবাজার সদর', 'distric_id' => 24],
                ['name' => 'Chakaria', 'bn_name' => 'চকরিয়া', 'distric_id' => 24],
                ['name' => 'Maheshkhali', 'bn_name' => 'মহেশখালি', 'distric_id' => 24],
                ['name' => 'Ramu', 'bn_name' => 'রামু', 'distric_id' => 24],
                ['name' => 'Ukhiya', 'bn_name' => 'উখিয়া', 'distric_id' => 24],
                ['name' => 'Teknaf', 'bn_name' => 'টেকনাফ', 'distric_id' => 24],
                ['name' => 'Kutubdia', 'bn_name' => 'কুতুবদিয়া', 'distric_id' => 24],
                ['name' => 'Khulna Sadar', 'bn_name' => 'খুলনা সদর', 'distric_id' => 25],
                ['name' => 'Batiaghata', 'bn_name' => 'বটিয়াঘাটা', 'distric_id' => 25],
                ['name' => 'Dumuria', 'bn_name' => 'ডুমুরিয়া', 'distric_id' => 25],
                ['name' => 'Dacope', 'bn_name' => 'ডাকোপ', 'distric_id' => 25],
                ['name' => 'Terokhada', 'bn_name' => 'তেরখাদা', 'distric_id' => 25],
                ['name' => 'Paikgachha', 'bn_name' => 'পাইকগাছা', 'distric_id' => 25],
                ['name' => 'Phultala', 'bn_name' => 'ফুলতলা', 'distric_id' => 25],
                ['name' => 'Rupsa', 'bn_name' => 'রূপসা', 'distric_id' => 25],
                ['name' => 'Koyra', 'bn_name' => 'কয়রা', 'distric_id' => 25],
                ['name' => 'Dighalia', 'bn_name' => 'দিঘলিয়া', 'distric_id' => 25],
                ['name' => 'Paikgachha', 'bn_name' => 'পাইকগাছা', 'distric_id' => 25],
                ['name' => 'Bagerhat', 'bn_name' => 'বাগেরহাট', 'distric_id' => 26],
                ['name' => 'Mongla', 'bn_name' => 'মংলা', 'distric_id' => 26],
                ['name' => 'Fultala', 'bn_name' => 'ফুলতলা', 'distric_id' => 26],
                ['name' => 'Jessore', 'bn_name' => 'যশোর', 'distric_id' => 27],
                ['name' => 'Jhenaidah', 'bn_name' => 'ঝিনাইদহ', 'distric_id' => 28],
                ['name' => 'Satkhira', 'bn_name' => 'সাতক্ষীরা', 'distric_id' => 29],
                ['name' => 'Khulna City', 'bn_name' => 'খুলনা শহর', 'distric_id' => 25],
                ['name' => 'Bagerhat Sadar', 'bn_name' => 'বাগেরহাট সদর', 'distric_id' => 26],
                ['name' => 'Mongla', 'bn_name' => 'মংলা', 'distric_id' => 26],
                ['name' => 'Fultala', 'bn_name' => 'ফুলতলা', 'distric_id' => 26],
                ['name' => 'Kachua', 'bn_name' => 'কচুয়া', 'distric_id' => 26],
                ['name' => 'Chitalmari', 'bn_name' => 'চিতলমারি', 'distric_id' => 26],
                ['name' => 'Mollahat', 'bn_name' => 'মোল্লাহাট', 'distric_id' => 26],
                ['name' => 'Rampal', 'bn_name' => 'রামপাল', 'distric_id' => 26],
                ['name' => 'Morrelganj', 'bn_name' => 'মোরেলগঞ্জ', 'distric_id' => 26],
                ['name' => 'Sarankhola', 'bn_name' => 'শরণখোলা', 'distric_id' => 26],
                ['name' => 'Chuadanga Sadar', 'bn_name' => 'চুয়াডাঙ্গা সদর', 'distric_id' => 27],
                ['name' => 'Alamdanga', 'bn_name' => 'আলমডাঙ্গা', 'distric_id' => 27],
                ['name' => 'Damurhuda', 'bn_name' => 'দামুড়হুদা', 'distric_id' => 27],
                ['name' => 'Jibannagar', 'bn_name' => 'জীবননগর', 'distric_id' => 27],
                ['name' => 'Jashore Sadar', 'bn_name' => 'যশোর সদর', 'distric_id' => 28],
                ['name' => 'Bagherpara', 'bn_name' => 'বাঘেরপাড়া', 'distric_id' => 28],
                ['name' => 'Chaugachha', 'bn_name' => 'চৌগাছা', 'distric_id' => 28],
                ['name' => 'Jhikargacha', 'bn_name' => 'ঝিকরগাছা', 'distric_id' => 28],
                ['name' => 'Keshabpur', 'bn_name' => 'কেশবপুর', 'distric_id' => 28],
                ['name' => 'Sharsha', 'bn_name' => 'শারশা', 'distric_id' => 28],
                ['name' => 'Manirampur', 'bn_name' => 'মনিরামপুর', 'distric_id' => 28],
                ['name' => 'Jhenaidah Sadar', 'bn_name' => 'ঝিনাইদহ সদর', 'distric_id' => 29],
                ['name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ', 'distric_id' => 29],
                ['name' => 'Kotchandpur', 'bn_name' => 'কোটচাঁদপুর', 'distric_id' => 29],
                ['name' => 'Maheshpur', 'bn_name' => 'মহেশপুর', 'distric_id' => 29],
                ['name' => 'Shailkupa', 'bn_name' => 'শৈলকুপা', 'distric_id' => 29],
                ['name' => 'Harinakunda', 'bn_name' => 'হরিণাকুন্ডু', 'distric_id' => 29],
                ['name' => 'Khulna Sadar', 'bn_name' => 'খুলনা সদর', 'distric_id' => 30],
                ['name' => 'Batiaghata', 'bn_name' => 'বটিয়াঘাটা', 'distric_id' => 30],
                ['name' => 'Dacope', 'bn_name' => 'ডাকোপ', 'distric_id' => 30],
                ['name' => 'Dumuria', 'bn_name' => 'ডুমুরিয়া', 'distric_id' => 30],
                ['name' => 'Terokhada', 'bn_name' => 'তেরখাদা', 'distric_id' => 30],
                ['name' => 'Phultala', 'bn_name' => 'ফুলতলা', 'distric_id' => 30],
                ['name' => 'Rupsa', 'bn_name' => 'রূপসা', 'distric_id' => 30],
                ['name' => 'Koyra', 'bn_name' => 'কয়রা', 'distric_id' => 30],
                ['name' => 'Paikgachha', 'bn_name' => 'পাইকগাছা', 'distric_id' => 30],
                ['name' => 'Kushtia Sadar', 'bn_name' => 'কুষ্টিয়া সদর', 'distric_id' => 31],
                ['name' => 'Bheramara', 'bn_name' => 'ভেড়ামারা', 'distric_id' => 31],
                ['name' => 'Kumarkhali', 'bn_name' => 'কুমারখালী', 'distric_id' => 31],
                ['name' => 'Daulatpur', 'bn_name' => 'দৌলতপুর', 'distric_id' => 31],
                ['name' => 'Mirpur', 'bn_name' => 'মিরপুর', 'distric_id' => 31],
                ['name' => 'Magura Sadar', 'bn_name' => 'মাগুরা সদর', 'distric_id' => 32],
                ['name' => 'Mohammadpur', 'bn_name' => 'মোহাম্মদপুর', 'distric_id' => 32],
                ['name' => 'Shalikha', 'bn_name' => 'শালিখা', 'distric_id' => 32],
                ['name' => 'Sreepur', 'bn_name' => 'শ্রীপুর', 'distric_id' => 32],
                ['name' => 'Meherpur Sadar', 'bn_name' => 'মেহেরপুর সদর', 'distric_id' => 33],
                ['name' => 'Gangni', 'bn_name' => 'গাংনী', 'distric_id' => 33],
                ['name' => 'Mujibnagar', 'bn_name' => 'মুজিবনগর', 'distric_id' => 33],
                ['name' => 'Narail Sadar', 'bn_name' => 'নড়াইল সদর', 'distric_id' => 34],
                ['name' => 'Kalia', 'bn_name' => 'কালিয়া', 'distric_id' => 34],
                ['name' => 'Lohagara', 'bn_name' => 'লোহাগাড়া', 'distric_id' => 34],
                ['name' => 'Satkhira Sadar', 'bn_name' => 'সাতক্ষীরা সদর', 'distric_id' => 35],
                ['name' => 'Kalaroa', 'bn_name' => 'কালারোয়া', 'distric_id' => 35],
                ['name' => 'Assasuni', 'bn_name' => 'আসসাসুনি', 'distric_id' => 35],
                ['name' => 'Debhata', 'bn_name' => 'দেবহাটা', 'distric_id' => 35],
                ['name' => 'Shyamnagar', 'bn_name' => 'শ্যামনগর', 'distric_id' => 35],
                ['name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ', 'distric_id' => 35],
                ['name' => 'Bogura Sadar', 'bn_name' => 'বগুড়া সদর', 'distric_id' => 36],
                ['name' => 'Shibganj', 'bn_name' => 'শিবগঞ্জ', 'distric_id' => 36],
                ['name' => 'Adamdighi', 'bn_name' => 'আদমদিঘি', 'distric_id' => 36],
                ['name' => 'Dhunat', 'bn_name' => 'ধুনাট', 'distric_id' => 36],
                ['name' => 'Gabtali', 'bn_name' => 'গাবতলী', 'distric_id' => 36],
                ['name' => 'Kahaloo', 'bn_name' => 'কাহালু', 'distric_id' => 36],
                ['name' => 'Nandigram', 'bn_name' => 'নন্দীগ্রাম', 'distric_id' => 36],
                ['name' => 'Sariakandi', 'bn_name' => 'সারিয়াকান্দি', 'distric_id' => 36],
                ['name' => 'Shajahanpur', 'bn_name' => 'শাজাহানপুর', 'distric_id' => 36],
                ['name' => 'Sonatola', 'bn_name' => 'সোনাতলা', 'distric_id' => 36],
                ['name' => 'Joypurhat Sadar', 'bn_name' => 'জয়পুরহাট সদর', 'distric_id' => 37],
                ['name' => 'Akkelpur', 'bn_name' => 'আক্কেলপুর', 'distric_id' => 37],
                ['name' => 'Kalai', 'bn_name' => 'কালাই', 'distric_id' => 37],
                ['name' => 'Khetlal', 'bn_name' => 'ক্ষেতলাল', 'distric_id' => 37],
                ['name' => 'Panchbibi', 'bn_name' => 'পঞ্চবিবি', 'distric_id' => 37],
                ['name' => 'Naogaon Sadar', 'bn_name' => 'নওগাঁ সদর', 'distric_id' => 38],
                ['name' => 'Atrai', 'bn_name' => 'আত্রাই', 'distric_id' => 38],
                ['name' => 'Badalgachhi', 'bn_name' => 'বদলগাছী', 'distric_id' => 38],
                ['name' => 'Manda', 'bn_name' => 'মান্দা', 'distric_id' => 38],
                ['name' => 'Naogaon Sadar', 'bn_name' => 'নওগাঁ সদর', 'distric_id' => 38],
                ['name' => 'Niamatpur', 'bn_name' => 'নিয়ামতপুর', 'distric_id' => 38],
                ['name' => 'Patnitala', 'bn_name' => 'পত্নীতলা', 'distric_id' => 38],
                ['name' => 'Porsha', 'bn_name' => 'পোর্শা', 'distric_id' => 38],
                ['name' => 'Raninagar', 'bn_name' => 'রাণীনগর', 'distric_id' => 38],
                ['name' => 'Sapahar', 'bn_name' => 'সাপাহার', 'distric_id' => 38],
                ['name' => 'Natore Sadar', 'bn_name' => 'নাটোর সদর', 'distric_id' => 39],
                ['name' => 'Baraigram', 'bn_name' => 'বড়াইগ্রাম', 'distric_id' => 39],
                ['name' => 'Bagatipara', 'bn_name' => 'বাগাতিপাড়া', 'distric_id' => 39],
                ['name' => 'Lalpur', 'bn_name' => 'লালপুর', 'distric_id' => 39],
                ['name' => 'Singra', 'bn_name' => 'সিংড়া', 'distric_id' => 39],
                ['name' => 'Chapai Nawabganj Sadar', 'bn_name' => 'চাপাই নবাবগঞ্জ সদর', 'distric_id' => 40],
                ['name' => 'Shibganj', 'bn_name' => 'শিবগঞ্জ', 'distric_id' => 40],
                ['name' => 'Nachole', 'bn_name' => 'নাচোল', 'distric_id' => 40],
                ['name' => 'Gomastapur', 'bn_name' => 'গোমস্তাপুর', 'distric_id' => 40],
                ['name' => 'Pabna Sadar', 'bn_name' => 'পাবনা সদর', 'distric_id' => 41],
                ['name' => 'Bera', 'bn_name' => 'বেড়া', 'distric_id' => 41],
                ['name' => 'Santhia', 'bn_name' => 'সাঁথিয়া', 'distric_id' => 41],
                ['name' => 'Chatmohar', 'bn_name' => 'চাটমোহর', 'distric_id' => 41],
                ['name' => 'Ishwardi', 'bn_name' => 'ঈশ্বরদী', 'distric_id' => 41],
                ['name' => 'Atghoria', 'bn_name' => 'আটঘোরিয়া', 'distric_id' => 41],
                ['name' => 'Sujanagar', 'bn_name' => 'সুজানগর', 'distric_id' => 41],
                ['name' => 'Bagha', 'bn_name' => 'বাঘা', 'distric_id' => 42],
                ['name' => 'Bagmara', 'bn_name' => 'বাগমারা', 'distric_id' => 42],
                ['name' => 'Charghat', 'bn_name' => 'চারঘাট', 'distric_id' => 42],
                ['name' => 'Durgapur', 'bn_name' => 'দুর্গাপুর', 'distric_id' => 42],
                ['name' => 'Godagari', 'bn_name' => 'গোদাগাড়ী', 'distric_id' => 42],
                ['name' => 'Mohanpur', 'bn_name' => 'মোহনপুর', 'distric_id' => 42],
                ['name' => 'Paba', 'bn_name' => 'পবা', 'distric_id' => 42],
                ['name' => 'Puthia', 'bn_name' => 'পুঠিয়া', 'distric_id' => 42],
                ['name' => 'Tanore', 'bn_name' => 'তানোর', 'distric_id' => 42],
                ['name' => 'Rajshahi Sadar', 'bn_name' => 'রাজশাহী সদর', 'distric_id' => 42],
                ['name' => 'Belkuchi', 'bn_name' => 'বেলকুচি', 'distric_id' => 43],
                ['name' => 'Chauhali', 'bn_name' => 'চৌহালি', 'distric_id' => 43],
                ['name' => 'Raiganj', 'bn_name' => 'রায়গঞ্জ', 'distric_id' => 43],
                ['name' => 'Shahjadpur', 'bn_name' => 'শাহজাদপুর', 'distric_id' => 43],
                ['name' => 'Sirajganj Sadar', 'bn_name' => 'সিরাজগঞ্জ সদর', 'distric_id' => 43],
                ['name' => 'Tarash', 'bn_name' => 'তারাশ', 'distric_id' => 43],
                ['name' => 'Ullahpara', 'bn_name' => 'উল্লাপাড়া', 'distric_id' => 43],
                ['name' => 'Kazipur', 'bn_name' => 'কাজীপুর', 'distric_id' => 43],
                ['name' => 'Kamarkhanda', 'bn_name' => 'কামারখন্দ', 'distric_id' => 43],
                ['name' => 'Raiganj', 'bn_name' => 'রায়গঞ্জ', 'distric_id' => 43],
                ['name' => 'Amtali', 'bn_name' => 'আমতলী', 'distric_id' => 44],
                ['name' => 'Bamna', 'bn_name' => 'বামনা', 'distric_id' => 44],
                ['name' => 'Barguna Sadar', 'bn_name' => 'বরগুনা সদর', 'distric_id' => 44],
                ['name' => 'Betagi', 'bn_name' => 'বেতাগি', 'distric_id' => 44],
                ['name' => 'Patharghata', 'bn_name' => 'পাথরঘাটা', 'distric_id' => 44],
                ['name' => 'Taltali', 'bn_name' => 'তালতলী', 'distric_id' => 44],
                ['name' => 'Agailjhara', 'bn_name' => 'আগৈলঝাড়া', 'distric_id' => 45],
                ['name' => 'Babuganj', 'bn_name' => 'বাবুগঞ্জ', 'distric_id' => 45],
                ['name' => 'Bakerganj', 'bn_name' => 'বাকেরগঞ্জ', 'distric_id' => 45],
                ['name' => 'Banaripara', 'bn_name' => 'বানারীপাড়া', 'distric_id' => 45],
                ['name' => 'Barishal Sadar', 'bn_name' => 'বরিশাল সদর', 'distric_id' => 45],
                ['name' => 'Gournadi', 'bn_name' => 'গৌরনদী', 'distric_id' => 45],
                ['name' => 'Hizla', 'bn_name' => 'হিজলা', 'distric_id' => 45],
                ['name' => 'Mehendiganj', 'bn_name' => 'মেহেন্দিগঞ্জ', 'distric_id' => 45],
                ['name' => 'Muladi', 'bn_name' => 'মূলাদী', 'distric_id' => 45],
                ['name' => 'Wazirpur', 'bn_name' => 'ওজিরপুর', 'distric_id' => 45],
                ['name' => 'Bhola Sadar', 'bn_name' => 'ভোলা সদর', 'distric_id' => 46],
                ['name' => 'Borhanuddin', 'bn_name' => 'বোরহানউদ্দিন', 'distric_id' => 46],
                ['name' => 'Char Fasson', 'bn_name' => 'চরফ্যাশন', 'distric_id' => 46],
                ['name' => 'Daulatkhan', 'bn_name' => 'দৌলতখান', 'distric_id' => 46],
                ['name' => 'Lalmohan', 'bn_name' => 'লালমোহন', 'distric_id' => 46],
                ['name' => 'Tazumuddin', 'bn_name' => 'তজুমদ্দিন', 'distric_id' => 46],
                ['name' => 'Jhalokati Sadar', 'bn_name' => 'ঝালকাঠি সদর', 'distric_id' => 47],
                ['name' => 'Nalchity', 'bn_name' => 'নলছিটি', 'distric_id' => 47],
                ['name' => 'Rajapur', 'bn_name' => 'রাজাপুর', 'distric_id' => 47],
                ['name' => 'Patuakhali Sadar', 'bn_name' => 'পটুয়াখালী সদর', 'distric_id' => 48],
                ['name' => 'Bauphal', 'bn_name' => 'বাউফল', 'distric_id' => 48],
                ['name' => 'Dashmina', 'bn_name' => 'দশমিনা', 'distric_id' => 48],
                ['name' => 'Galachipa', 'bn_name' => 'গলাচিপা', 'distric_id' => 48],
                ['name' => 'Kalapara', 'bn_name' => 'কালাপারা', 'distric_id' => 48],
                ['name' => 'Rangabali', 'bn_name' => 'রাঙ্গাবালি', 'distric_id' => 48],
                ['name' => 'Pirojpur Sadar', 'bn_name' => 'পিরোজপুর সদর', 'distric_id' => 49],
                ['name' => 'Bhandaria', 'bn_name' => 'ভাণ্ডারিয়া', 'distric_id' => 49],
                ['name' => 'Kawkhali', 'bn_name' => 'কাউখালি', 'distric_id' => 49],
                ['name' => 'Mathbaria', 'bn_name' => 'মঠবাড়িয়া', 'distric_id' => 49],
                ['name' => 'Nesarabad (Swarupkathi)', 'bn_name' => 'নেছারাবাদ (স্বরূপকাঠি)', 'distric_id' => 49],
                ['name' => 'Zianagar', 'bn_name' => 'জিয়ানগর', 'distric_id' => 49],
                ['name' => 'Habiganj Sadar', 'bn_name' => 'হবিগঞ্জ সদর', 'distric_id' => 50],
                ['name' => 'Ajmiriganj', 'bn_name' => 'আজমিরীগঞ্জ', 'distric_id' => 50],
                ['name' => 'Baniachong', 'bn_name' => 'বানিয়াচং', 'distric_id' => 50],
                ['name' => 'Bahubal', 'bn_name' => 'বাহুবল', 'distric_id' => 50],
                ['name' => 'Chunarughat', 'bn_name' => 'চুনারুঘাট', 'distric_id' => 50],
                ['name' => 'Madhabpur', 'bn_name' => 'মাধবপুর', 'distric_id' => 50],
                ['name' => 'Moulvibazar Sadar', 'bn_name' => 'মৌলভীবাজার সদর', 'distric_id' => 51],
                ['name' => 'Kulaura', 'bn_name' => 'কুলাউরা', 'distric_id' => 51],
                ['name' => 'Juri', 'bn_name' => 'জুড়ি', 'distric_id' => 51],
                ['name' => 'Rajnagar', 'bn_name' => 'রাজনগর', 'distric_id' => 51],
                ['name' => 'Sreemangal', 'bn_name' => 'শ্রীমঙ্গল', 'distric_id' => 51],
                ['name' => 'Kamalgonj', 'bn_name' => 'কমলগঞ্জ', 'distric_id' => 51],
                ['name' => 'Sunamganj Sadar', 'bn_name' => 'সুনামগঞ্জ সদর', 'distric_id' => 52],
                ['name' => 'Derai', 'bn_name' => 'দিরাই', 'distric_id' => 52],
                ['name' => 'Jagannathpur', 'bn_name' => 'জগন্নাথপুর', 'distric_id' => 52],
                ['name' => 'Dowarabazar', 'bn_name' => 'দোয়ারাবাজার', 'distric_id' => 52],
                ['name' => 'Chhatak', 'bn_name' => 'ছাতক', 'distric_id' => 52],
                ['name' => 'Shalla', 'bn_name' => 'শাল্লা', 'distric_id' => 52],
                ['name' => 'Tahirpur', 'bn_name' => 'তাহিরপুর', 'distric_id' => 52],
                ['name' => 'Jagannathpur', 'bn_name' => 'জগন্নাথপুর', 'distric_id' => 52],
                ['name' => 'Sunamganj Sadar', 'bn_name' => 'সুনামগঞ্জ সদর', 'distric_id' => 53],
                ['name' => 'Bishwamvarpur', 'bn_name' => 'বিশ্বম্ভরপুর', 'distric_id' => 53],
                ['name' => 'Chhatak', 'bn_name' => 'ছাতক', 'distric_id' => 53],
                ['name' => 'Dakshin Sunamganj', 'bn_name' => 'দক্ষিণ সুনামগঞ্জ', 'distric_id' => 53],
                ['name' => 'Derai', 'bn_name' => 'দিরাই', 'distric_id' => 53],
                ['name' => 'Jagannathpur', 'bn_name' => 'জগন্নাথপুর', 'distric_id' => 53],
                ['name' => 'Jamalganj', 'bn_name' => 'জামালগঞ্জ', 'distric_id' => 53],
                ['name' => 'Sullah', 'bn_name' => 'সুল্লা', 'distric_id' => 53],
                ['name' => 'Shanthiganj', 'bn_name' => 'শান্তিগঞ্জ', 'distric_id' => 53],
                ['name' => 'Tahirpur', 'bn_name' => 'তাহিরপুর', 'distric_id' => 53],
                ['name' => 'Birampur', 'bn_name' => 'বিরামপুর', 'distric_id' => 54],
                ['name' => 'Biral', 'bn_name' => 'বিরল', 'distric_id' => 54],
                ['name' => 'Birganj', 'bn_name' => 'বীরগঞ্জ', 'distric_id' => 54],
                ['name' => 'Bochaganj', 'bn_name' => 'বচাগঞ্জ', 'distric_id' => 54],
                ['name' => 'Chirirbandar', 'bn_name' => 'চিরিরবন্দর', 'distric_id' => 54],
                ['name' => 'Dinajpur Sadar', 'bn_name' => 'দিনাজপুর সদর', 'distric_id' => 54],
                ['name' => 'Ghoraghat', 'bn_name' => 'ঘোড়াঘাট', 'distric_id' => 54],
                ['name' => 'Hakimpur', 'bn_name' => 'হাকিমপুর', 'distric_id' => 54],
                ['name' => 'Kaharole', 'bn_name' => 'কাহারোল', 'distric_id' => 54],
                ['name' => 'Parbatipur', 'bn_name' => 'পার্বতীপুর', 'distric_id' => 54],
                ['name' => 'Phulbari', 'bn_name' => 'ফুলবাড়ী', 'distric_id' => 54],
                ['name' => 'Birol', 'bn_name' => 'বীরল', 'distric_id' => 54],
                ['name' => 'Palashbari', 'bn_name' => 'পলাশবাড়ী', 'distric_id' => 55],
                ['name' => 'Sadullapur', 'bn_name' => 'সদুল্লাপুর', 'distric_id' => 55],
                ['name' => 'Sundarganj', 'bn_name' => 'সুন্দরগঞ্জ', 'distric_id' => 55],
                ['name' => 'Gaibandha Sadar', 'bn_name' => 'গাইবান্ধা সদর', 'distric_id' => 55],
                ['name' => 'Gobindaganj', 'bn_name' => 'গোবিন্দগঞ্জ', 'distric_id' => 55],
                ['name' => 'Palashbari', 'bn_name' => 'পলাশবাড়ী', 'distric_id' => 55],
                ['name' => 'Phulchhari', 'bn_name' => 'ফুলছড়ি', 'distric_id' => 55],
                ['name' => 'Saghata', 'bn_name' => 'সাঘাটা', 'distric_id' => 55],
                ['name' => 'Phulbari', 'bn_name' => 'ফুলবাড়ী', 'distric_id' => 56],
                ['name' => 'Kurigram Sadar', 'bn_name' => 'কুড়িগ্রাম সদর', 'distric_id' => 56],
                ['name' => 'Ulipur', 'bn_name' => 'উলিপুর', 'distric_id' => 56],
                ['name' => 'Nageshwari', 'bn_name' => 'নাগেশ্বরী', 'distric_id' => 56],
                ['name' => 'Rajarhat', 'bn_name' => 'রাজারহাট', 'distric_id' => 56],
                ['name' => 'Bhurungamari', 'bn_name' => 'ভুরুঙ্গামারী', 'distric_id' => 56],
                ['name' => 'Chilmari', 'bn_name' => 'চিলমারি', 'distric_id' => 56],
                ['name' => 'Rowmari', 'bn_name' => 'রৌমারী', 'distric_id' => 56],
                ['name' => 'Char Rajibpur', 'bn_name' => 'চর রাজিবপুর', 'distric_id' => 56],
                ['name' => 'Lalmonirhat Sadar', 'bn_name' => 'লালমনিরহাট সদর', 'distric_id' => 57],
                ['name' => 'Aditmari', 'bn_name' => 'আদিতমারী', 'distric_id' => 57],
                ['name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ', 'distric_id' => 57],
                ['name' => 'Hatibandha', 'bn_name' => 'হাতিবান্ধা', 'distric_id' => 57],
                ['name' => 'Nilphamari Sadar', 'bn_name' => 'নীলফামারী সদর', 'distric_id' => 58],
                ['name' => 'Dimla', 'bn_name' => 'ডিমলা', 'distric_id' => 58],
                ['name' => 'Domar', 'bn_name' => 'ডোমার', 'distric_id' => 58],
                ['name' => 'Jaldhaka', 'bn_name' => 'জলঢাকা', 'distric_id' => 58],
                ['name' => 'Panchagarh Sadar', 'bn_name' => 'পঞ্চগড় সদর', 'distric_id' => 59],
                ['name' => 'Atwari', 'bn_name' => 'আটওয়ারী', 'distric_id' => 59],
                ['name' => 'Debiganj', 'bn_name' => 'দেবীগঞ্জ', 'distric_id' => 59],
                ['name' => 'Boda', 'bn_name' => 'বোদা', 'distric_id' => 59],
                ['name' => 'Rangpur Sadar', 'bn_name' => 'রংপুর সদর', 'distric_id' => 60],
                ['name' => 'Badarganj', 'bn_name' => 'বাদারগঞ্জ', 'distric_id' => 60],
                ['name' => 'Mithapukur', 'bn_name' => 'মিঠাপুকুর', 'distric_id' => 60],
                ['name' => 'Gangachara', 'bn_name' => 'গাঙ্গাচড়া', 'distric_id' => 60],
                ['name' => 'Kaunia', 'bn_name' => 'কাউনিয়া', 'distric_id' => 60],
                ['name' => 'Pirganj', 'bn_name' => 'পীরগঞ্জ', 'distric_id' => 60],
                ['name' => 'Taraganj', 'bn_name' => 'তারাগঞ্জ', 'distric_id' => 60],
                ['name' => 'Thakurgaon Sadar', 'bn_name' => 'ঠাকুরগাঁও সদর', 'distric_id' => 61],
                ['name' => 'Baliadangi', 'bn_name' => 'বালিয়াডাঙ্গি', 'distric_id' => 61],
                ['name' => 'Haripur', 'bn_name' => 'হরিপুর', 'distric_id' => 61],
                ['name' => 'Pirganj', 'bn_name' => 'পীরগঞ্জ', 'distric_id' => 61],
                ['name' => 'Ranisankail', 'bn_name' => 'রাণীশংকৈল', 'distric_id' => 61],
                ['name' => 'Jamalpur Sadar', 'bn_name' => 'জামালপুর সদর', 'distric_id' => 62],
                ['name' => 'Baksiganj', 'bn_name' => 'বাকসিগঞ্জ', 'distric_id' => 62],
                ['name' => 'Dewanganj', 'bn_name' => 'দেওয়ানগঞ্জ', 'distric_id' => 62],
                ['name' => 'Islampur', 'bn_name' => 'ইসলামপুর', 'distric_id' => 62],
                ['name' => 'Madarganj', 'bn_name' => 'মাদারগঞ্জ', 'distric_id' => 62],
                ['name' => 'Sarishabari', 'bn_name' => 'সারিশাবারি', 'distric_id' => 62],
                ['name' => 'Mymensingh Sadar', 'bn_name' => 'ময়মনসিংহ সদর', 'distric_id' => 63],
                ['name' => 'Bhaluka', 'bn_name' => 'ভালুকা', 'distric_id' => 63],
                ['name' => 'Trishal', 'bn_name' => 'ত্রিশাল', 'distric_id' => 63],
                ['name' => 'Muktagachha', 'bn_name' => 'মুক্তাগাছা', 'distric_id' => 63],
                ['name' => 'Nandail', 'bn_name' => 'নান্দাইল', 'distric_id' => 63],
                ['name' => 'Gaffargaon', 'bn_name' => 'গফরগাঁও', 'distric_id' => 63],
                ['name' => 'Phulpur', 'bn_name' => 'ফুলপুর', 'distric_id' => 63],
                ['name' => 'Netrokona Sadar', 'bn_name' => 'নেত্রকোনা সদর', 'distric_id' => 64],
                ['name' => 'Durgapur', 'bn_name' => 'দূর্গাপুর', 'distric_id' => 64],
                ['name' => 'Kalmakanda', 'bn_name' => 'কালমাকান্দা', 'distric_id' => 64],
                ['name' => 'Khaliajuri', 'bn_name' => 'খালিয়াজুরি', 'distric_id' => 64],
                ['name' => 'Mohanganj', 'bn_name' => 'মোহনগঞ্জ', 'distric_id' => 64],
                ['name' => 'Purbadhala', 'bn_name' => 'পূর্বধলা', 'distric_id' => 64],
                ['name' => 'Sherpur Sadar', 'bn_name' => 'শেরপুর সদর', 'distric_id' => 65],
                ['name' => 'Jhenaigati', 'bn_name' => 'ঝিনাইগাতী', 'distric_id' => 65],
                ['name' => 'Nakla', 'bn_name' => 'নকলা', 'distric_id' => 65],
                ['name' => 'Nalitabari', 'bn_name' => 'নালিতাবাড়ী', 'distric_id' => 65],
                ['name' => 'Sreebardi', 'bn_name' => 'শ্রীবরদী', 'distric_id' => 65],


            


        ];
         DB::table('upzilas')->insert($upzilas_list);
    }
}
