<option value="India">India </option>
<option value="Nepal">Nepal </option>
<option value="Sri lanka">Sri lanka </option>
<option value="EU">EU </option>
<option value="USA">USA </option>
<option value="Saudi Arabia">Saudi Arabia </option>
<option value="Qatar">Qatar </option>
<option value="Lebanon">Lebanon </option>
<option value="Irag">Irag </option>
<option value="UAE">UAE </option>
<option value="Thailand">Thailand </option>
<option value="Vietnam">Vietnam </option>
<option value="Cambodia">Cambodia </option>
<option value="South Africa">South Africa </option>
<option value="Brazil">Brazil </option>
<option value="UK">UK </option>
